---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.1
    env:
#1.Раздел часной информации, неделитесь даннмы из этого раздела!
#1.Private information section, do not share data from this section!
     - "my_root_password=31081988" # пароль root для подключения по ssh
     - "MONIKER=Dimokus_Akash" # имя ноды
     - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
#==================================================================
#2.Раздел переменных для работы ноды
#2.Section of variables for node operation 
     - "binary=autonomy"
     - "vers=v1.2.1"
     - "genesis=https://raw.githubusercontent.com/ravaliGangasani/Network/main/genesis.json"
     - "folder=.autonomy"
     - "denom=uaut"
     - "chain=autonomy"
     - "gitrep=https://github.com/AutonomyNetwork/autonomy-chain.git"
     - "gitfold=autonomy-chain"
     - "link_peer=https://raw.githubusercontent.com/Dimokus88/Autonomy/main/PEERS"
     - "link_seed=https://raw.githubusercontent.com/Dimokus88/Autonomy/main/SEED" 
     - "SNAP_RPC="
     - "SHIFT=1000"
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s  https://raw.githubusercontent.com/Dimokus88/universe/main/main.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 80Gi
        
        
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
